# -*- coding: utf-8 -*-
# 版172 変異試験: 1箇所ずつ壊して、試験が赤くなるか確かめる（現場入力）
#   版172 は「保存先を『物件 ＞ リスト』に固定する」版。
#     PC   … 物件のフォルダを選んでも中の「リスト」を覚える（親も覚える）。前の版で覚えたルートも寄せる。
#             ルートにできてしまった写しは、保存のたびに写真を和集合にしてリストへ（ルートは消さない）。
#     スマホ … 受付台帳を取り込むと入れる場所が「物件名/リスト」に決まる。案内も入れない所まで言う。
import io, subprocess, os
HERE = os.path.dirname(os.path.abspath(__file__))
SP = os.path.join(HERE, "..") + os.sep
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
MAIN = os.environ.get("MAIN") or os.path.join(ROOT, "antenna_main", "index.html")
GENBA = os.environ.get("GENBA") or os.path.join(ROOT, "antenna_genba", "index.html")
OUTM = os.path.join(HERE, "mut_main.html")
OUTG = os.path.join(HERE, "mut_genba.html")
CR = lambda x: x.replace("\r\n", "\n").replace("\n", "\r\n")

# (名前, 壊す前, 壊した後, 試験, どちらのファイル)
CASES = [
  (u"★1-1 「リスト」という名前で決めない（中が空の新しい物件で、物件のすぐ下に書く）",
   u'''      if(!named && saveDirIsListName(name)){ named = { dir:h, name:name, strong:true }; continue; }''',
   u'''      void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-1 特別記録を戸別の数に入れる",
   u'''!/^現場用|^受付台帳|^特別記録_/.test(name)) n++;''',
   u'''!/^現場用|^受付台帳/.test(name)) n++;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-2 強い手がかりでも中へ入るか聞く（押す回数が増える）",
   u'''  if(f && !f.strong){''',
   u'''  if(f){''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-2 まとめて保存で選んだフォルダをそのまま覚える（物件のすぐ下に書く）",
   u'''      dir = await saveDirAdopt(dir, { ask:false });''',
   u'''      await saveDirSet(dir);''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-3 保存（1件）で、前の版で覚えたルートをリストへ寄せない",
   u'''     ただし黙って別の道へ行くと「いつもと違う画面が出た」理由が分からないので、あとで伝える。 */
  let dirLapsed = false;
  if(dir && !(await saveDirOk(dir, false))){ dir = null; dirLapsed = true; }
  if(dir) dir = await saveDirSettle(dir);    // 前の版で物件のフォルダを覚えていたら、中の「リスト」へ寄せる''',
   u'''     ただし黙って別の道へ行くと「いつもと違う画面が出た」理由が分からないので、あとで伝える。 */
  let dirLapsed = false;
  if(dir && !(await saveDirOk(dir, false))){ dir = null; dirLapsed = true; }''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-3 特別記録の保存で、前の版で覚えたルートをリストへ寄せない",
   u'''  /* 戸別の「保存」と同じ。許可が切れているときは聞き直さずに落として、あとで伝える。 */
  let dirLapsed = false;
  if(dir && !(await saveDirOk(dir, false))){ dir = null; dirLapsed = true; }
  if(dir) dir = await saveDirSettle(dir);    // 前の版で物件のフォルダを覚えていたら、中の「リスト」へ寄せる''',
   u'''  /* 戸別の「保存」と同じ。許可が切れているときは聞き直さずに落として、あとで伝える。 */
  let dirLapsed = false;
  if(dir && !(await saveDirOk(dir, false))){ dir = null; dirLapsed = true; }''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-3 寄せられないフォルダを、保存のたびに総なめする",
   u'''  if(_saveDirChecked.has(dir)) return dir;''',
   u'''  void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-4 覚えるフォルダを替えても、前の物件で当たったフォルダ・名前の一覧を捨てない",
   u'''  _caseDirHit = null; _caseDirHitRoot = null; _cfIdx = null;''',
   u'''  void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-5 保存バーに「物件 ＞ リスト」を出さない（どこへ入れているか見えない）",
   u'''  const destHtml = (dest && destPP.outer && destPP.inner)''',
   u'''  const destHtml = (false && destPP.outer && destPP.inner)''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-5 「＞ リスト」の max-width を消す（中の名前が長いと「変更」が画面の外へ）",
   u'''  .sb-dest-in{ flex:none; max-width:8em; overflow:hidden; text-overflow:ellipsis;''',
   u'''  .sb-dest-in{ flex:none; overflow:hidden; text-overflow:ellipsis;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-5 「＞ リスト」を縮む箱に戻す（長い物件名で「＞ リ…」まで削られる）",
   u'''  .sb-dest-in{ flex:none; max-width:8em; overflow:hidden; text-overflow:ellipsis;''',
   u'''  .sb-dest-in{ flex:0 1 auto; min-width:3em; max-width:8em; overflow:hidden; text-overflow:ellipsis;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-6 根元（物件）が違っても、前に当たったフォルダを先に見る（前の物件のファイルを読む）",
   u'''  if(_caseDirHit && _caseDirHitRoot === root && _caseDirHit !== dir){''',
   u'''  if(_caseDirHit && _caseDirHit !== dir){''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-7 リストとルートの両方にあるとき（リストが新しい）、ルートの写しを和集合に入れない（写真が落ちる）",
   u'''    else cf.others = cf.others.concat([cp.primary], cp.others);''',
   u'''    else void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-7 ルートにだけあるとき、ルートの写しを土台にしない（写真・PCの中身が消える）",
   u'''  if(!cf.primary){ cf.primary = cp.primary; cf.pick = cp.pick; cf.others = cf.others.concat(cp.others); }''',
   u'''  if(!cf.primary){ }''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-7 両方にあるとき、控えを古い扱いにしない（現場の値が土台の値に黙って戻る）",
   u'''    cf.rootPrimary = cp.primary;''',
   u'''    void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-7 控えがリストの中身と合っていても古い扱いにする（毎回確かめの窓が出る）",
   u'''  if(baseFitsFile(b, cf.primary)) return b;              // 控え＝土台の中身''',
   u'''  void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★1-9 📥 で物件のすぐ下のファイルを読まない（スマホが前の案内どおり入れた分を取りこぼす）",
   u'''          if(h && h.kind === "file" && /\\.json(\\.txt)?$/i.test(h.name)) out.push({ name: h.name, handle: h });''',
   u'''          void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★2-4 案内で「物件の中のリスト」と言わない（名前1つの言い方に戻る）",
   u'''  if(pp.outer) return "''',
   u'''  if(false) return "''',
   "smoke_v172_genba.js", "genba"),
  (u"★2-4 特別記録を共有で渡したとき、入れる場所を言わない",
   u'''        + saveHintLine()
        + shareRenameNote(sr.as) + lapsedLine(), warn:true };''',
   u'''        + shareRenameNote(sr.as) + lapsedLine(), warn:true };''',
   "smoke_v172_genba.js", "genba"),
  (u"★2-2 受付台帳を取り込んでも、入れる場所を決めない",
   u'''  try{ if(saveHintAuto(src && src.project, oldProj)) renderSaveBar(); }catch(_){}''',
   u'''  void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★2-2 自分で選んだ名前まで書き替える",
   u'''  if(mine) return "";''',
   u'''  void 0;''',
   "smoke_v172_genba.js", "genba"),
  (u"★2-5 保存中の暗幕に「入れる所」を出さない",
   u'''    + (where ? ('<div class="save-ov-s">入れる所：' + esc(where) + "</div>") : "")''',
   u'''    + ""''',
   "smoke_v172_genba.js", "genba"),
  # ---- 反証を生き延びた指摘の直し（工事フォルダ・リストの中の子・PCの名前だけの道）と、試験の抜け ----
  (u"★修1 弱い手がかりで「はい」と答えたとき、中のリストまで降りない（物件Aのすぐ下を覚える）",
   u"""    const t = await saveDirInto(f.dir, picked);""",
   u"""    const t = { dir:f.dir, parent:picked };""",
   "smoke_v172_genba.js", "genba"),
  (u"★修1 中のリストへ入れないのに覚え直す（物件Aのすぐ下を親つきで覚える）",
   u"""    if(!(await saveDirOk(f.dir, false))) return null;""",
   u"""    void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修1 中のリストへ降りるとき、許可を聞き直す（押した操作を使ってしまう）",
   u"""    if(!(await saveDirOk(f.dir, false))) return null;""",
   u"""    if(!(await saveDirOk(f.dir, true))) return null;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修1 根元が物件と確かめずに子を見る（工事フォルダの下の別の物件を読んで、ここへ書く）",
   u"""  if(root !== dir && !(await saveDirRootIsProj(root, dir))) return null;""",
   u"""  void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修2 PC（フォルダを選べる端末）でも、取り込みで名前だけの入れる場所を決める（「未設定 選ぶ」が消える）",
   u"""  if(window.showDirectoryPicker) return "";""",
   u"""  void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修2 PC の取り込みの知らせに、名前だけの入れる場所を出す",
   u"""(saveHintWhere() && !window.showDirectoryPicker && !saveDirName())""",
   u"""(saveHintWhere() && !saveDirName())""",
   "smoke_v172_genba.js", "genba"),
  (u"★修4 まとめて保存で、ルートの写しを読み合わせない（写真・PCだけの中身が入らない）",
   u"""        const cf0 = await readCaseFilesForWrite(dir, f.name, f.no);""",
   u"""        const cf0 = await readExistingCaseFiles(dir, f.name, f.no);""",
   "smoke_v172_genba.js", "genba"),
  (u"★修4 まとめて保存で、控えを古い扱いにしない（現場の値がリストの古い値に黙って戻る）",
   u"""          const base0 = baseForWrite(b0, cf0);   // 物件のすぐ下にも同じ戸別があったとき""",
   u"""          const base0 = b0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修5 「覚えない」を選んだ印を残さない（次の取り込みで入れる場所が黙って戻る）",
   u"""      try{ localStorage.setItem(LS_SAVEHINT_AUTO,
        !got ? "\\u0000off" : ((proj && got === proj + "/リスト") ? got : "")); }catch(_){}""",
   u"""      void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修6 親（物件）を IndexedDB に残さない（開き直すと親が消える）",
   u"""  try{ await idbMapPut({ key:SAVEDIR_KEY, handle:h, parent:(h && parent) || null,""",
   u"""  try{ await idbMapPut({ key:SAVEDIR_KEY, handle:h, parent:null,""",
   "smoke_v172_genba.js", "genba"),
  (u"★修6 開き直したとき、親（物件）を戻さない",
   u"""    _saveDirPar = (_saveDir && r.parent)""",
   u"""    _saveDirPar = (false && r.parent)""",
   "smoke_v172_genba.js", "genba"),
  (u"★修7 保存の読み合わせで、物件のフォルダの許可を聞き直す",
   u"""  if(!(await saveDirOk(par, false))) return cf;""",
   u"""  if(!(await saveDirOk(par, true))) return cf;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修7 リストへ寄せるとき、リストの許可を聞き直す",
   u"""  if(!(await saveDirOk(f.dir, false))) return dir;""",
   u"""  if(!(await saveDirOk(f.dir, true))) return dir;""",
   "smoke_v172_genba.js", "genba"),
  (u"★修7 📥 で、物件のフォルダの許可を聞き直す",
   u"""      if(await saveDirOk(par, false)){""",
   u"""      if(await saveDirOk(par, true)){""",
   "smoke_v172_genba.js", "genba"),
  (u"★修8 前の版の履歴に残った「物件名だけ」を候補に出す",
   u"""  const notBare = h => !proj || h !== proj;""",
   u"""  const notBare = h => true;""",
   "smoke_v172_genba.js", "genba"),
  # ---- 版172 第1回の直し（反証で潰せなかったもの） ----
  (u"★直1 工事フォルダを覚えているとき、「物件」らしい子（中に「リスト」／台帳）まで読む（別の物件の迷子を開いて、そこへ書く）",
   u"""      if(root === list && (await saveDirLooksProj(h))) continue;""",
   u"""      void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直1 中に「リスト」がある子を「物件」と見なさない",
   u"""      if(h.kind === "directory" && saveDirIsListName(name)) return true;""",
   u"""      void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直1 受付台帳がある子を「物件」と見なさない",
   u"""      if(h.kind === "file" && SAVEDIR_LEDGER_RE.test(name)) return true;""",
   u"""      void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直1 読んで当たった所に合わせて保存先を覚え直す（外した仕組みを戻す：別の物件のリストへ移る）",
   u"""     保存先は、選んだとき（saveDirAdopt）と前の版の覚えを寄せるとき（saveDirSettle）の確かな手がかりだけで決める。 */
  return true;""",
   u"""     保存先は、選んだとき（saveDirAdopt）と前の版の覚えを寄せるとき（saveDirSettle）の確かな手がかりだけで決める。 */
  try{ if(hit.dir && hit.dir !== dir && !hit.fromRoot && dir === _saveDir && !saveDirParentOf(dir)){
    const t = await saveDirInto(hit.dir, dir); if(t){ await saveDirSet(t.dir, t.parent); } } }catch(_){}
  return true;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直2 「リスト」そのものを選んで（覚えて）いても、中へ降りる（中の「完了」へ黙って移る）",
   u"""  if(!dir || saveDirIsListName(dir.name)) return null;""",
   u"""  if(!dir) return null;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直2 「完了」などの子も保存先の候補にする",
   u"""      if(saveDirSkipChild(name) || saveDirOldChild(name)) continue;""",
   u"""      if(saveDirSkipChild(name)) continue;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直3 同じフォルダかを isSameEntry で確かめない（本物ではいつも「違う」）",
   u"""  try{ if(typeof a.isSameEntry === "function") return (await a.isSameEntry(b)) === true; }catch(_){}""",
   u"""  void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直3 根元が物件かを === で比べる（本物では、リストを覚えていても物件の中の子を見なくなる）",
   u"""  return !!(f && f.strong && (await saveDirSame(f.dir, dir)));""",
   u"""  return !!(f && f.strong && f.dir === dir);""",
   "smoke_v172_genba.js", "genba"),
  (u"★直3 もう見たフォルダを === で比べる（本物では、覚えているリストをもう一度読む）",
   u"""      if((await saveDirSame(h, list)) || (await saveDirSame(h, _caseDirHit))) continue;  // もう見た""",
   u"""      if(h === list || h === _caseDirHit) continue;  // もう見た""",
   "smoke_v172_genba.js", "genba"),
  (u"★直4→直9 「控え≠すぐ下の写し」だけで「PCがリストを直した」と決めつける（消した行を戻す）",
   u"""  return Object.assign({}, b, { stale:true });           // 出どころが確かでない → 値の見比べをやめる（1件保存では1回聞く）""",
   u"""  if(!baseFitsFile(b, cf.rootPrimary)) return b;
  return Object.assign({}, b, { stale:true });""",
   "smoke_v172_genba.js", "genba"),
  (u"★直5 前の版で「覚えない」を選んだ端末でも、取り込むと入れる場所を決め直す",
   u"""    if(h === ""){ try{ localStorage.setItem(LS_SAVEHINT_AUTO, "\\u0000off"); }catch(_){} return ""; }""",
   u"""    void 0;""",
   "smoke_v172_genba.js", "genba"),
  # ---- 版172 第2回の直し（反証で潰せなかったもの） ----
  (u"★直6 台帳の目印で拡張子を見ない（受付台帳_まとめ.xlsx でも強い手がかりになる）",
   u"""const SAVEDIR_LEDGER_RE = /^(現場用|受付台帳).*\\.json(\\.txt)?$/i;""",
   u"""const SAVEDIR_LEDGER_RE = /^(現場用|受付台帳)/;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直7 リストから取った控えでも、ルートの写しに合えば古い扱いにする（PCの直しが現場の古い値へ戻る）",
   u"""  if(b.from === "list" && cf.primary !== cf.rootPrimary) return b;   // 土台はリスト、控えもリストから（PCがリストを直した）""",
   u"""  void 0;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直7 控えに出どころの印を残さない",
   u"""stale: false, from: String(from || ""),""",
   u"""stale: false, from: "",""",
   "smoke_v172_genba.js", "genba"),
  (u"★直7 1件保存でリストへ書いた控えに「リスト」の印を付けない",
   u"""      fileBaseAfterWrite(M, state, fname, primary, mgKeys, saveDirParentOf(dir) ? "list" : "root");""",
   u"""      fileBaseAfterWrite(M, state, fname, primary, mgKeys, "root");""",
   "smoke_v172_genba.js", "genba"),
  (u"★直7 まとめて保存でリストへ書いた控えに「リスト」の印を付けない",
   u"""f.cf && f.cf.primary, f.keys, saveDirParentOf(dir) ? "list" : "root"); }""",
   u"""f.cf && f.cf.primary, f.keys, "root"); }""",
   "smoke_v172_genba.js", "genba"),
  (u"★直7 リストから開いた控えに「リスト」の印を付けない",
   u"""  if(M._fileBase) M._fileBase.from = (!hit.fromRoot && hit.dir === dir && saveDirParentOf(dir)) ? "list" : "root";""",
   u"""  if(M._fileBase) M._fileBase.from = "root";""",
   "smoke_v172_genba.js", "genba"),
  (u"★直7 ルートの写しから開いた控えにも「リスト」の印を付ける（現場の値がリストの古い値へ戻る）",
   u"""  if(M._fileBase) M._fileBase.from = (!hit.fromRoot && hit.dir === dir && saveDirParentOf(dir)) ? "list" : "root";""",
   u"""  if(M._fileBase) M._fileBase.from = "list";""",
   "smoke_v172_genba.js", "genba"),
  (u"★直8 リストを覚えていて戸別がルートにだけあるとき、開いてもルートの写しを読まない",
   u"""    const h3 = await look(root);""",
   u"""    const h3 = null;""",
   "smoke_v172_genba.js", "genba"),
  # ---- 版172 第3回の直し（反証で潰せなかったもの） ----
  (u"★直9 両方にあるとき、新しい方（ルートの写し）を土台にしない（古いリストを土台にして、PCの直しと現場の前の入力が消える）",
   u"""    if(tr > tl){""",
   u"""    if(false){""",
   "smoke_v172_genba.js", "genba"),
  (u"★直9 ルートの写しが土台のとき、古い方（リスト）を和集合に入れない（リストにしか無い写真が落ちる）",
   u"""    if(tr > tl){ cf.others = [cf.primary].concat(cf.others, cp.others); cf.primary = cp.primary; cf.pick = cp.pick; }""",
   u"""    if(tr > tl){ cf.others = cf.others.concat(cp.others); cf.primary = cp.primary; cf.pick = cp.pick; }""",
   "smoke_v172_genba.js", "genba"),
  (u"★直9 控えがどちらとも言えないとき、見比べを続ける（黙って決めつける）",
   u"""  return Object.assign({}, b, { stale:true });           // 出どころが確かでない → 値の見比べをやめる（1件保存では1回聞く）""",
   u"""  return b;""",
   "smoke_v172_genba.js", "genba"),
  (u"★直9 土台がルートの写しでも、リストから取った控えで見比べる（現場の値を黙ってルートの値へ替える）",
   u"""  if(b.from === "list" && cf.primary !== cf.rootPrimary) return b;""",
   u"""  if(b.from === "list") return b;""",
   "smoke_v172_genba.js", "genba"),
  # ---- 版172 第4回（Claude）：減らして、迷ったら聞く ----
  (u"★第4回 「リスト」を探すとき、中のフォルダ20個で打ち切る（番号のフォルダが並ぶ物件で見落とし、物件のすぐ下へ書く）",
   u"""      if(kids.length < 20) kids.push([name, h]);           // 数えるのは20個まで（名前は最後まで見る）""",
   u"""      if(kids.length >= 20) break;
      kids.push([name, h]);""", "smoke_v172_genba.js", "genba"),
  (u"★第4回 受付台帳を強い手がかりに戻す（台帳がリストの中・工事フォルダにあると、リストの外や別の物件へ書く）",
   u"""  best.strong = false;                    // 名前が「リスト」でなければ、いつも弱い手がかり""",
   u"""  best.strong = here === 0;""", "smoke_v172_genba.js", "genba"),
  (u"★第4回 印の無い控え（出どころが確かでない）でも見比べる（ルートから取った控えで、現場の入力が黙って戻る）",
   u"""  return Object.assign({}, b, { stale:true });           // 出どころが確かでない → 値の見比べをやめる（1件保存では1回聞く）""",
   u"""  if(!b.from) return b;
  return Object.assign({}, b, { stale:true });""", "smoke_v172_genba.js", "genba"),
  (u"★第4回 帯の📁で見つからないとき、どこを探したか（物件 ＞ リスト）を言わない",
   u"""(saveDirPlace() || dir.name || "選んだフォルダ") + "」の中に、この戸別のファイルが見つかりませんでした。""",
   u"""(dir.name || "選んだフォルダ") + "」の中に、この戸別のファイルが見つかりませんでした。""", "smoke_v172_genba.js", "genba"),
  (u"★第4回 帯の📁で、覚えているフォルダの許可が切れていても聞き直さない（押しても読み込めない）",
   u"""    if(!(await saveDirOk(dir, true))){              // 許可が切れていたら、ここで聞き直す""",
   u"""    if(!(await saveDirOk(dir, false))){""", "smoke_v172_genba.js", "genba"),
  # ---- 版172 第5回（Claude）：まとめて保存は、出どころの確かでない控えで書かずに残す ----
  (u"★第5回 まとめて保存で、出どころの確かでない控えのまま この端末の値を書く（PCがリストで直した値が黙って戻る）",
   u"""          if(base0 !== b0 && !baseUseValues(base0) && (mg0.mine.length || mg0.conflicts.length)){""",
   u"""          if(false){""", "smoke_v172_genba.js", "genba"),
  (u"★第5回 まとめて保存で書かなかった戸別を知らせない",
   u"""    if(unsureNos.length){""",
   u"""    if(false){""", "smoke_v172_genba.js", "genba"),
  (u"★第5回 書かなかった戸別も「渡した」扱いにする（まとめて保存から外れて取り残される）",
   u"""            unsureNos.push(f.no); ngNos.push(f.no); continue;""",
   u"""            unsureNos.push(f.no); okNos.push(f); continue;""", "smoke_v172_genba.js", "genba"),
]

import sys as _s
_only = _s.argv[1] if len(_s.argv) > 1 else ""
red = 0; n_run = 0
for name, old, new, test, which in CASES:
    if _only and _only not in name: continue
    n_run += 1
    src, OUT = (GENBA, OUTG) if which == "genba" else (MAIN, OUTM)
    base = io.open(src, encoding="utf-8", newline="").read()
    o, n = CR(old), CR(new)
    if base.count(o) != 1:
        print("SKIP（目印 %d 件）: %s" % (base.count(o), name)); continue
    io.open(OUT, "w", encoding="utf-8", newline="").write(base.replace(o, n))
    r = subprocess.run(["node", SP + test, "file://" + OUT], capture_output=True, text=True, timeout=900)
    last = [l for l in (r.stdout + r.stderr).splitlines() if l.startswith("- ")][:1]
    isred = r.returncode != 0
    if isred: red += 1
    print(("赤 ✓" if isred else "緑 ✗（検出できていない）"), name, "|", " / ".join(x[:120] for x in last))
print("=== 赤 %d / %d ===" % (red, n_run))
